# Generated by Django 4.1 on 2023-11-19 05:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile_is_premium'),
    ]

    operations = [
        migrations.CreateModel(
            name='Premium',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('subsc_descrp', ckeditor.fields.RichTextField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
