# Generated by Django 4.1 on 2023-11-19 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_premium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='premium',
            old_name='subsc_descrp',
            new_name='plan_descrp',
        ),
        migrations.RenameField(
            model_name='premium',
            old_name='name',
            new_name='plan_name',
        ),
        migrations.RenameField(
            model_name='premium',
            old_name='price',
            new_name='plan_price',
        ),
    ]
