# Generated by Django 4.1 on 2023-11-19 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_subsc_descrp_premium_plan_descrp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='premium',
            name='plan_price',
            field=models.CharField(max_length=10),
        ),
    ]
