# Generated by Django 4.1 on 2023-11-20 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_premium_plan_descrp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='premium_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='premium_status',
            field=models.BooleanField(default=False),
        ),
    ]
