# Generated by Django 4.1 on 2023-11-21 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_profile_premium_expiry_date_profile_premium_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Travel', 'Travel'), ('Food and Drink', 'Food and Drink'), ('Health and Fitness', 'Health and Fitness'), ('Technology', 'Technology'), ('Business and Finance', 'Business and Finance'), ('Personal Development', 'Personal Development'), ('Arts and Entertainment', 'Arts and Entertainment'), ('Sports', 'Sports'), ('News and Politics', 'News and Politics'), ('Lifestyle', 'Lifestyle'), ('Coding and Programming', 'Coding and Programming'), ('Science and Technology', 'Science and Technology')], max_length=255, null=True),
        ),
    ]
